image: docker
services:
  - docker:dind

variables:
  GITLAB_SHARED_DIND_DIR: /builds/$CI_PROJECT_PATH/shared

stages:
  - build

.prepare_build: &prepare_build
  - ls -l
  - pwd
  - apk add bash
  - mkdir -p "$GITLAB_SHARED_DIND_DIR" && chmod 777 "$GITLAB_SHARED_DIND_DIR"
  - if echo "$CI_COMMIT_BRANCH" | grep -Eq '(release|testing)'; then export BUILD_ALL_DISTROS=1; fi

.prepare_artfacts: &prepare_artfacts
  - mkdir output
  - cp -r builder/build/* output/
  - rm output/*.tar.gz

before_script:
  - *prepare_build
after_script:
  - *prepare_artfacts

build_ubuntu_bionic:
  stage: build
  script:
    - bash builder/build-distro ubuntu bionic
  artifacts:
    paths:
      - output/

build_ubuntu_focal:
  stage: build
  script:
    - if [ -n "$BUILD_ALL_DISTROS" ]; then
        bash builder/build-distro ubuntu focal;
      fi
  artifacts:
    paths:
      - output/

build_debian_buster:
  stage: build
  script:
    - if [ -n "$BUILD_ALL_DISTROS" ]; then
        bash builder/build-distro debian buster;
      fi
  artifacts:
    paths:
      - output/

build_debian_bullseye:
  stage: build
  script:
    - if [ -n "$BUILD_ALL_DISTROS" ]; then
        bash builder/build-distro debian bullseye;
      fi
  artifacts:
    paths:
      - output/

build_kali_rolling:
  stage: build
  script:
    - if [ -n "$BUILD_ALL_DISTROS" ]; then
        bash builder/build-distro kali kali-rolling;
      fi
  artifacts:
    paths:
      - output/

build_centos7:
  stage: build
  script:
    - bash builder/build-distro centos core
  artifacts:
    paths:
      - output/
